{% set version = "0.2-7" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-circstats
  version: {{ version|replace("-", "_") }}

source:
  fn: CircStats_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/CircStats_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/CircStats/CircStats_{{ version }}.tar.gz
  sha256: 9f6dabe94c21cdc3c5330779e5a50a2cefb03cfc925a095bdc3ffa7af830e456

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-boot

  run:
    - r-base
    - r-mass
    - r-boot

test:
  commands:
    - $R -e "library('CircStats')"  # [not win]
    - "\"%R%\" -e \"library('CircStats')\""  # [win]

about:
  home: S-plus original at http://statweb.calpoly.edu/lund/
  license: GPL-2.0-only
  summary: Circular Statistics, from "Topics in circular Statistics" (2001) S. Rao Jammalamadaka and A. SenGupta, World Scientific.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
