travis:
  secure:
    BINSTAR_TOKEN: hE7Iqas4Ot1IFoIq/vU7b2Cdo9mffGkJVucQk8E+rUCskOnZFz7KMKgNN17GjX/tcXokYfCyw0sstMMoC944wkujtGDh2/d4ZAWf0GiyR4tbKQlJJexBnz0ouEsd7VPGnA+EbBUnPcHH7uqt1akBICAsN2KznoyD34S5pCOC0vYMgBpYQgrLH9Ybq95MgxxyORG/kNneFRD2dEouRhXRa+sFFmIHUFZog7AN/LbRmN4APyF3WsDnD6gFQX9hQXbAouummRfvQTur7qu1FuzwoZ4NsQlCZb0dQBcfJ11UwaBaaRS8BYHojkwCvyHjJ0FuZ7xw9hMYhqTgRu6vT2ytqZZ9Yn+bAYnh2EbipoROlN40qLGOXZCNW0n9s+xswHY4XLQPlJGp+rfeDIN6+AIu07pfZOCBfziOTXx+/+8o9kcE5BjPq4T2bt90dL3MO043QLT0NzKJf6AW8PyAtrz0cNI0kBCp0n0RLPFNGI+6z0dv5X2WVGx1Bur1YY6dL0rXcRQyN5kH6muk8M7iN+pNTwSzpkuWr2mnTD3faHkax8bxZJNxi07X1QAwTCq4eI4CukaHshOLnyN535hgLhpKlvcVPrwJcSDBxDiUnL4TR++nWOiJg9Jpal+aD6yqmDhsn5TBi465SXslWWZ1Pg7PmsGU9sqiXCg1k2o8f6CGYVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
