appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JjtTCeFBDAeYvSlh1zF4bc/gSZSASwH7zw+bIBKceepgAdBaMPyk62U4bN3OnpCuRSJVIeiqMYVFPdywnPsEVPIWYt/DP0TapP/l4ne7bPch9qfH0SpF6oPwAVcxDWTz/d+D8l2vSKafHH510CsAVdRnODZVnMPsEZx+BmCCZskwESubRuvN20G6dNiGiPXkYgCQBnLEueUL3/yyfk9s2E5MZJkVX1D/hRM8H/uiNwYY1p9BT7Bxr2HxP+eohXa/Yg8hWUfoAuxvQqHk3AJ3bIXmhg11sJrexct2eL1ZbIbgiIELPb39zVcSKx7/0DUWcJ8BW0CYCUj2O/COPBEWnL0aij/a8UlHgHwON8ja2/icVq3ldAwVQ3tWvk0EHIFIl45m6VvsiWEPLzGJdGGIlrbkOWqfzHdc0cVyg0ZhJSJFQU1Vjma/qKuFTD+jg0V6GsZc93u+j4odscEmbGBZOxaTpMH3SRhbdEOBIDc1q1HPlXJKlkGYq+TS6h8ObPY0xHVrOo2ktbirzYFtkChJ0nc5kr1izboKl54miGFhyEsz6Fx7tS2bnRlx+Jgv0vGSUmgA+4VD2i2O5vN5iIU+pOtPr95qLo7Zv6dY36gZjm1LnCxUfLH1JhTBTaCStVFMOJo27iy/e5aJFgxQjUrIryJOnZEFW664bnZ3Gi1clZQ=}
