travis:
  secure:
    BINSTAR_TOKEN: CdzrARL2jl+IOdv3fqWiEn3kujnlMLnXl7T1YGU/82B1IHGDCzq//B4YPuXvEr9a+IICbeQyYoXFo+F6umWzNy4zFNs+8kcAV1FNVU+/+1RWTMdyppSw/mIhe0Q3aZEDQj3CIu8R1egXggJ9UfTCo3ZSvX4TVLTHVL50N0/WAynkWRBy0XcBaMFpM3ylURgtG6x3vhufJNXhx1ILPsAc8gIyKSKd61AV+aA51ej6iNtOP1oSKEqF8XrhNR5lPL/S66WhEXXf+Eo3ahYZejyXjrF1ghHAFnQ/fdurt4qv8jjvkuVJTCdc91FK0KftYEyyt1UK0kc1surlCNPSzHyIsuGvVUr5LFyiGrcqCSoWz6iOGd4od787etULREILR1EGj2XjWWCRW7VJ06OJM5ouoy2SzXRkkm3cFiidoSszT81xTYMQglIYcKF3Ypg/AZjxmv9nc1jdXzN2hcK4T2MQH0im15yvfsT0k/SnwE38GPuOkjwtV2i3LCxfqIn1YsVBmzLLwupJeBp6W68BJTHTbMVCdVXbYM0E0ShvSTAY5bBJ4ZEPSKJrKQuf+g1ycInfywlw9QaK2wKuLzW/sWH9yByLRKQ2JytvlsvkUPZRNurgRl6Mp7C8eBcR9X1oUgjwtpMdeT94y8NtqEsyZKjxJ8kAjYZT2dVQYUW+Ypm7fmc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
